[package]
name = "dotreg"
version = "0.1.0"
authors = ["Renée Kooi <renee@kooi.me>"]
edition = "2018"

[dependencies]
bstr = "^0.1.4"
encoding_rs = "^0.8.17"
encoding_rs_io = "^0.1.6"
nom = "^5.0.0-beta2"
